### ISSUE TITLE
Compatibility: Let Julia v1.0-v1.4 be able to use it

### ISSUE THREAD

**Issue by singularitti** [KeitaNakamura/Tensorial.jl#132]
It seems that this package only [works on Julia v1.5 and above](https://github.com/KeitaNakamura/Tensorial.jl/blob/cce423c30ab57c3ed3a5f03b499dc53b66aa23fd/Project.toml#L15). Is there a specific feature that requires v1.5+? If not, could we make it v1.0-v1.4 compatible?

**Comment by KeitaNakamura** [comment]
In Julia v1.0-1.4, the syntax `@Symmetry{a, b}` is not available (you need to write `@Symmetry({a, b})` instead), but other features seem to be fine.

**Comment by KeitaNakamura** [comment]
Please try after #135 is merged.
