### ISSUE TITLE
Compilation Time Long when N > 50

### ISSUE THREAD

**Issue by ejmeitz** [KeitaNakamura/Tensorial.jl#225]
Is the compilation time for the Tensor types expected to take order of minutes?

I tested:
` make_sym = (N) -> rand(Tensor{Tuple{@Symmetry{N,N,N}},Float32})`
and it took about a minute to compile with N = 100. 
`@Mat rand(50,50)` also took around a minute.

I was interested to benchmark the symmetry specific optimizations, but my use case is at least tensors that are 600x600x600 and the compilation time is making that impossible. Am I using something wrong or is this package only intended for small amounts of data?

**Comment by KeitaNakamura** [comment]
Yes, this package is designed for handling only small-sized tensors, similar to SArray in StaticArrays.jl. I think you should take a look at [TensorOperatios.jl](https://github.com/Jutho/TensorOperations.jl) and [Tullio.jl](https://github.com/mcabbott/Tullio.jl).

**Comment by ejmeitz** [comment]
Already using TensorOperations was just looking to see if this could be useful. I actually want something that does sparse contractions but I think I'll have to stick with my own code for that.

Package looks great for the smaller stuff though.

**Comment by KeitaNakamura** [comment]
Thanks. I'm not familiar with sparse structures, but [TensorKit.jl](https://github.com/Jutho/TensorKit.jl) might be useful? Perhaps you've already looked into it, though.
